collections:
  authors:
   output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


  # Output true was an issue until I got to the end section of part 9. I have no idea why It's working now. Ohh geez